### PR TITLE
Saving memory

### PR DESCRIPTION
**Pull request by Sumanthjois**
Creating all the opertional objects(Addition etc)  as class members will use up some memory in the heap if you dont use them also. So it's better if you create them in switch case statements so that they will on be created when required and save some memory.

### CODE REVIEW

**Comment by piq9117** [comment]
Thank you!

**Comment by Sumanthjois** [comment]
Welcome! are you guys done with just two projects?? Or do you have any more?

**Comment by piq9117** [comment]
We occasionally play with Java but we have our hands full with javascript right now, especially with React-flux-redux.

**Comment by Sumanthjois** [comment]
can  i know the repository name! i will try contributing something

**Pull request merged**
